databrary/datavyu-ffmpegplugin

- src/main/cpp/FrameQueue.hpp
- src/main/cpp/PacketQueue.hpp
- src/main/cpp/TestFrameQueue.cpp
This resolves task DVD-370
Frame queue
Removes compile errors
Adds tests
> Task dvd 370

- README.md
- src/main/cpp/Clock.hpp
- src/main/cpp/Decoder.hpp
- src/main/cpp/FFplay.vcxproj
- src/main/cpp/FFplay.vcxproj.filters
- src/main/cpp/FrameQueue.hpp
- src/main/cpp/PacketQueue.hpp
- src/main/cpp/TestDecoder.cpp
- src/main/cpp/VideoState.h
- src/main/cpp/ffplay.cpp
Integrates Clock, PacketQueue, and FrameQueue into ffplay.cpp
Test with 'counter.mp4' worked for me and closes w/out problems
> Task dvd 373

- .gitattributes
- src/main/cpp/Decoder.hpp
- src/main/cpp/FFplay.vcxproj
- src/main/cpp/FFplay.vcxproj.filters
- src/main/cpp/FrameQueue.hpp
- src/main/cpp/PacketQueue.hpp
- src/main/cpp/ffplay.cpp
Integrated Decoder
Minor clean-up of code
Replaced SDL_thread through std::thread for reading data
Added .gitattributes for binary merge strategy on some files
Corrected notify all to notify one which should have been used in the first place
> Task dvd 391

- src/main/cpp/FfmpegJavaAvPlayback.cpp
- src/main/cpp/FfmpegMediaPlayer.cpp
- src/main/java/org/datavyu/plugins/ffmpeg/MediaPlayerData.java
- src/main/java/org/datavyu/plugins/ffmpeg/examples/SimpleMediaPlayerExample.java
- Corrected double clean-up removed exit(0)
- Adjusted example program
> Fix for crash during destroy

- src/main/cpp/FfmpegAvPlayback.cpp
- src/main/cpp/FfmpegAvPlayback.h
- src/main/cpp/FfmpegJavaAvPlayback.cpp
- src/main/cpp/FfmpegJavaAvPlayback.h
- src/main/cpp/FfmpegJavaAvPlaybackPipline.cpp
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.h
- src/main/cpp/FfmpegSdlAvPlaybackPipeline.cpp
- src/main/cpp/FrameQueue.cpp
- src/main/cpp/FrameQueue.h
- src/main/cpp/TestFrameQueue.cpp
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
- src/main/cpp/ffplay.cpp
Reverts databrary/datavyu-ffmpegplugin#37
> Revert "Proper error handling when allocating memory"

- src/main/cpp/Decoder.cpp
- src/main/cpp/Decoder.h
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.h
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
- Replaced bridge functions for decoder through lambda function
- Replaced bridge for reader thread through lambda function
> Remove bridges for reader threads and decode thread

- src/main/java/org/datavyu/plugins/ffmpeg/ImageCanvasPlayerThread.java
- src/main/java/org/datavyu/plugins/ffmpeg/ImagePlayerThread.java
Reverts databrary/datavyu-ffmpegplugin#47
> Revert "DVD-467 Scale image while resizing the frame"

- src/main/cpp/VideoState.cpp
- src/main/java/org/datavyu/plugins/ffmpeg/ImageCanvasPlayerThread.java
- src/main/java/org/datavyu/plugins/ffmpeg/examples/SimpleJavaMediaPlayer.java
- src/test/java/org/datavyu/plugins/ffmpeg/TestPlaybackRate.java
- Only change the rate if different from the current one
(A rate change from 1->1 caused the queues to flush, the packet queues
increase their serial to 1 and the clocks to start running before
starting the playback)
> Fix change of playback rate

- src/main/cpp/FfmpegAvPlayback.cpp
- src/main/cpp/FfmpegJavaAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/VideoState.cpp
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegJavaMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/ImageCanvasPlayerThread.java
- src/main/java/org/datavyu/plugins/ffmpeg/examples/SimpleJavaFXMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/examples/SimpleJavaMediaPlayer.java
- Enabled step after seek to display seek frame, moved stop after step
into display block
- Fixed step in java code by pulling a frame after entering stepping
mode which will stop the clocks again
> Fix of step in native code

- src/main/cpp/FfmpegAvPlayback.cpp
- src/main/cpp/FfmpegAvPlayback.h
- src/main/cpp/FfmpegJavaAvPlaybackPipline.cpp
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlaybackPipeline.cpp
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
- src/main/java/org/datavyu/plugins/ffmpeg/ImageCanvasPlayerThread.java
- Corrected to take rate (instead of rate_found)
- Return error code when rate is not supported
> Hotfix for rate adjustemnt

- pom.xml
- src/main/cpp/FfmpegSdlAvPlayback.cpp
> Fix Compiler Error, Add Windows Profile with msbuild exec

- pom.xml
- src/main/java/org/datavyu/util/LibraryLoader.java
Added:
- Profiles to generate platforms-dependent dependency; ffmpeg and avFoundation for Mac OS and ffmpeg and MPV for WIndows
- Switched the distribution management to OJO
- Handle Mac dependencies for Mac
- closes #82
> Add Platforms dependent dependencies for the player

- pom.xml
> Add Source plugin to jar goal

- src/main/cpp/FfmpegAvPlayback.cpp
- src/main/cpp/FfmpegJavaAvPlaybackPipline.cpp
- src/main/cpp/MpvAvPlayback.h
- src/main/cpp/MpvAvPlaybackPipeline.cpp
- src/main/cpp/VideoState.cpp
- src/main/java/org/datavyu/plugins/MediaPlayer.java
- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/examples/JMediaPlayerControlFrame.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Fix Pause/Stop State Transition

- .gitignore
- pom.xml
- Add Debug and Release profiles for Mac
> Add xcode build to maven life cycles #143

- pom.xml
> Add compiler plugin config to exclude MPV and examples pkg #145

- src/main/cpp/FfmpegAvPlayback.h
- src/main/cpp/FfmpegJavaAvPlayback.cpp
- src/main/cpp/FfmpegJavaAvPlaybackPipline.cpp
- src/main/cpp/FfmpegJavaAvPlaybackPipline.h
- src/main/cpp/FfmpegJavaMediaPlayer.cpp
- src/main/cpp/FrameQueue.h
- src/main/cpp/Pipeline.h
- src/main/cpp/PipelineData.h
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
- src/main/cpp/org_datavyu_plugins_ffmpeg_FfmpegJavaMediaPlayer.h
- src/main/java/org/datavyu/plugins/MediaPlayer.java
- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/examples/JMediaPlayerControlFrame.java
- src/main/java/org/datavyu/plugins/examples/SimpleJavaMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegJavaMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegSdlMediaPlayer.java
- src/main/java/org/datavyu/plugins/mpv/MpvAwtMediaPlayer.java
- src/main/java/org/datavyu/plugins/mpv/MpvFxMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
> Add Seek to a specific frame feature

- src/main/cpp/FfmpegAvPlayback.cpp
- src/main/cpp/FfmpegJavaAvPlayback.cpp
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
> Add frame_last_shown_time_ variable initialization

- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegMediaPlayer.java
- src/main/java/org/datavyu/plugins/mpv/MpvMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Add start time to Native Media Player

- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Fix AVFoundation player count when destroying resources

- src/main/cpp/FfmpegJavaAvPlaybackPipline.cpp
- src/main/cpp/VideoState.cpp
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Fix Native OSX prev rate when seeking after a pause

- README.md
- pom.xml
- src/main/java/org/datavyu/plugins/MediaPlayerData.java
- Attach javadoc
- Add bintray and artifactory deploy profiles
- exclude plugins examples
- update dependencies version
> Bump version to 0.19

- pom.xml
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Fix AVFoundation Rate Transitions

- pom.xml
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.h
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegMediaPlayer.java
> Release FFmpeg-plugin 0.21

- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegMediaPlayer.java
> Restore player mute status after a seek 

- pom.xml
- src/main/cpp/FfmpegSdlAvPlaybackPipeline.cpp
- src/main/cpp/VideoState.cpp
- src/main/cpp/VideoState.h
- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- Fix NaN Presentation time values
- Bump to 0.22 SNAPSHOT
- Fixes #184
>  Fix Deadlock when seeking 

- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.h
closes #189
closes https://github.com/databrary/datavyu/issues/249
> Show cursor on top of SDL window 

- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/java/org/datavyu/plugins/examples/SimpleSdlMediaPlayer.java
> Fix SDL memory leak when wrong file path 

- src/main/cpp/Pipeline.cpp
closes #194
closes https://github.com/databrary/datavyu/issues/278
> Use correct Java Code for SDLK_KP_MINUS 

- src/main/java/org/datavyu/plugins/examples/JMediaPlayerControlFrame.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
- src/test/java/org/datavyu/plugins/ffmpeg/MediaPlayerSync.java
- src/test/java/org/datavyu/plugins/ffmpeg/MediaPlayerTest.java
- Remove Seek to frame calls
- Fix Play for time test and update supported states
- closes #212
> Fix AVFoundation player state transition

- src/main/java/org/datavyu/util/LibraryLoader.java
> Overwrite existing libraries when extracting dependencies.

- src/main/cpp/FfmpegAvPlayback.h
- src/main/cpp/VideoState.cpp
- wire step backward to video state seek
- closes #221
> Subtract 1/frame_rate from seek time

- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
- src/test/java/org/datavyu/plugins/ffmpeg/AVFoundationPlayerTest.java
- src/test/java/org/datavyu/plugins/ffmpeg/FfmpegSdlMediaPlayerTest.java
- src/test/java/org/datavyu/plugins/ffmpeg/MediaPlayerTest.java
- Add Unit Test to cover this corner case
> Overload play method with rate parameter closes #232

- demo/SimpleSdlMediaPlayer.java
- src/main/cpp/FfmpegSdlAvPlayback.cpp
- src/main/cpp/FfmpegSdlAvPlayback.h
- src/main/cpp/FfmpegSdlAvPlaybackPipeline.cpp
- src/main/cpp/FfmpegSdlAvPlaybackPipeline.h
- src/main/cpp/FfmpegSdlMediaPlayer.cpp
- src/main/cpp/Pipeline.h
- src/main/cpp/org_datavyu_plugins_ffmpeg_FfmpegSdlMediaPlayer.h
- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegJavaMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegSdlMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
> Fix sdl resize

- README.md
- demo/JMediaPlayerControlFrame.java
- demo/SimpleJavaFXMediaPlayer.java
- demo/SimpleSdlMediaPlayer.java
- src/main/cpp/JavaPlayerEventDispatcher.cpp
- src/main/java/org/datavyu/plugins/DatavyuMediaPlayer.java
- src/main/java/org/datavyu/plugins/MediaPlayer.java
- src/main/java/org/datavyu/plugins/MediaPlayerWindow.java
- src/main/java/org/datavyu/plugins/NativeMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegJavaMediaPlayer.java
- src/main/java/org/datavyu/plugins/ffmpeg/FfmpegSdlMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/AVFoundationMediaPlayer.java
- src/main/java/org/datavyu/plugins/nativeosx/NativeOSXMediaPlayer.java
- src/main/java/org/datavyu/util/LibraryLoader.java
- src/main/java/org/datavyu/util/Utils.java
- Code refactoring
- Code cleaning
> Enable Container controls for Native OSX plugin closes #236

- README.md
- pom.xml
> Bump Ffmpeg plugin version to 0.23 
